# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'level5.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_level5Dialog(object):
    def setupUi(self, level5Dialog):
        level5Dialog.setObjectName("level5Dialog")
        level5Dialog.resize(602, 353)
        self.map = QtWidgets.QTableWidget(level5Dialog)
        self.map.setGeometry(QtCore.QRect(10, 10, 400, 200))
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.map.setIconSize(QtCore.QSize(35, 35))
        self.map.setRowCount(5)
        self.map.setColumnCount(10)
        self.map.setObjectName("map")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.map.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.map.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.map.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.map.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fuel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.map.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.map.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        item.setBackground(brush)
        self.map.setItem(4, 3, item)
        self.map.horizontalHeader().setVisible(False)
        self.map.verticalHeader().setVisible(False)
        self.textEdit = QtWidgets.QTextEdit(level5Dialog)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 220, 401, 121))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.carButton = QtWidgets.QPushButton(level5Dialog)
        self.carButton.setEnabled(False)
        self.carButton.setGeometry(QtCore.QRect(130, 40, 40, 40))
        self.carButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carButton.setIcon(icon1)
        self.carButton.setIconSize(QtCore.QSize(36, 36))
        self.carButton.setCheckable(False)
        self.carButton.setFlat(True)
        self.carButton.setObjectName("carButton")
        self.homeButton = QtWidgets.QPushButton(level5Dialog)
        self.homeButton.setEnabled(False)
        self.homeButton.setGeometry(QtCore.QRect(150, 100, 40, 40))
        self.homeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon2)
        self.homeButton.setIconSize(QtCore.QSize(36, 36))
        self.homeButton.setCheckable(False)
        self.homeButton.setFlat(True)
        self.homeButton.setObjectName("homeButton")
        self.prgText = QtWidgets.QTextEdit(level5Dialog)
        self.prgText.setGeometry(QtCore.QRect(420, 60, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prgText.setFont(font)
        self.prgText.setObjectName("prgText")
        self.pushButton = QtWidgets.QPushButton(level5Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(level5Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(level5Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.powerLcd = QtWidgets.QLCDNumber(level5Dialog)
        self.powerLcd.setGeometry(QtCore.QRect(420, 10, 171, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.powerLcd.setPalette(palette)
        self.powerLcd.setAutoFillBackground(True)
        self.powerLcd.setDigitCount(2)
        self.powerLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.powerLcd.setProperty("intValue", 99)
        self.powerLcd.setObjectName("powerLcd")

        self.retranslateUi(level5Dialog)
        self.pushButton.clicked.connect(level5Dialog.playClicked)
        self.pushButton_2.clicked.connect(level5Dialog.saveClicked)
        self.pushButton_3.clicked.connect(level5Dialog.resetClicked)
        QtCore.QMetaObject.connectSlotsByName(level5Dialog)

    def retranslateUi(self, level5Dialog):
        _translate = QtCore.QCoreApplication.translate
        level5Dialog.setWindowTitle(_translate("level5Dialog", "LEVEL 5"))
        __sortingEnabled = self.map.isSortingEnabled()
        self.map.setSortingEnabled(False)
        item = self.map.item(2, 4)
        item.setWhatsThis(_translate("level5Dialog", "fuel"))
        self.map.setSortingEnabled(__sortingEnabled)
        self.textEdit.setHtml(_translate("level5Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Seviye 5</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Artık benzin eve gitmeye yetmiyor. yoldaki kırmızı benzin istasyonuna uğrayıp depo doldurarak  devam edin.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Bu bölümde kullanabileceğiniz komutlar:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">fulle():</span><span style=\" font-size:8pt;\"> bu komutu benzin istasyonunda kullanırsanız aracınızın deposu tekrar dolu hale gelecektir. Dijital sayaçta kaç adım yol gidebileceğiniz gösteriliyor.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">sağa(x):</span><span style=\" font-size:8pt;\"> bu komutu kullanırsanız sağa doğru x adım atarsınız eğer x değeri girmezseniz 1 adım atılacaktır. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">sola(x): </span><span style=\" font-size:8pt;\">sola doğru x adım atmak için kullanılır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">yukarı(x):</span><span style=\" font-size:8pt;\"> yukarı doğru x adım atmak için kullanılır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">aşağı(x):</span><span style=\" font-size:8pt;\"> aşağı doğru x adım atmak için kullanılır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">play </span><span style=\" font-size:8pt;\">tuşu ile yazdığınız kodu deneyebilirsiniz. Kolay gelsin..</span></p></body></html>"))
        self.prgText.setPlaceholderText(_translate("level5Dialog", "Kodunuzu buraya yazın.."))
        self.pushButton.setText(_translate("level5Dialog", "PLAY"))
        self.pushButton_2.setText(_translate("level5Dialog", "SAVE"))
        self.pushButton_3.setText(_translate("level5Dialog", "RESET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    level5Dialog = QtWidgets.QDialog()
    ui = Ui_level5Dialog()
    ui.setupUi(level5Dialog)
    level5Dialog.show()
    sys.exit(app.exec_())

